status = [
    "fmt",
    "licenses_and_advisories (advisories)",
    "licenses_and_advisories (bans licenses sources)",
    "linter",
    "msrv",
    "test (stable)",
    "test (beta)",
    "test (nightly)",
    "test (win-gnu)",
    "test (win-msvc)",
]
