[package]
name = "miniview"
version = "0.4.1"
authors = ["Martijn Gribnau <garm@ilumeo.com>"]
edition = "2018"
license = "Apache-2.0"
readme = "README.md"
repository = "https://github.com/foresterre/miniview"
description = "Display an image within a (graphical) window. Callable from a CLI interface."
keywords = ["image", "display", "graphical"]
categories = ["graphics", "command-line-utilities"]
exclude = ["resources/*", ".idea", "*.iml", ".vscode"]

[features]
default = ["backend_piston_window"]
backend_piston_window = ["piston_window"]
backend_pixels = ["pixels", "winit"]

[dependencies]
image = "0.23.12"
clap = "2.33.3"

# backend_piston_window
piston_window = { version = "0.117.0", optional = true }

# backend_pixels
pixels = { version = "0.2.0", optional = true }
winit = { version = "0.24.0", optional = true }
winit_input_helper = { version = "0.9.0", optional = true }

anyhow = "1.0.38"
thiserror = "1.0.23"

[dev-dependencies]
assert_cmd = "1.0.2"
parameterized = "0.3.1"
