[licenses]
unlicensed = "deny"
copyleft = "deny"
confidence-threshold = 0.925
allow = [
    "Apache-2.0",
    "BSD-2-Clause",
    "BSD-2-Clause-FreeBSD",
    "BSD-3-Clause",
    "CC0-1.0",
    "ISC",
    "MIT",
    "MPL-2.0",
    "Unlicense",
    "Zlib",
    "Unicode-DFS-2016",
]

[[licenses.clarify]]
name = "exr"
expression = "BSD-3-Clause"
license-files = [
    { path = "LICENSE.md", hash = 0xf0600744 },
]


[advisories]
ignore = [
    # nix v0.18.0 - NB: Update available
    # ├── calloop v0.6.5 - NB: Update available
    # │   └── smithay-client-toolkit v0.12.3 - NB: Update available
    # │       └── winit v0.25.0 - NB: Update available, but unreleased (as of 2021-10-10)
    # │           └── winit_input_helper v0.10.0 - NB: Depends on winit v0.25.0
    # │               └── miniview v0.5.1
    # └── smithay-client-toolkit v0.12.3 (*)
    "RUSTSEC-2021-0119",

]



