name: "ci-linter"
on:
  pull_request:
  push:
    branches:
      - master
      - main
      - staging # for Bors
      - trying # for Bors
  merge_group:
jobs:
  linter:
    name: linter
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - name: checkout_repo
        uses: actions/checkout@v4

      - name: install_rust
        uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy

      - name: check_with_clippy_backend_pixels
        run: cargo clippy --all-targets --no-default-features --features backend_pixels -- -D warnings

      - name: check_with_clippy_backend_piston_window
        run: cargo clippy --all-targets --no-default-features --features backend_piston_window -- -D warnings
